from . import hr_hospital_person
from . import hr_hospital_patient
from . import hr_hospital_doctor
from . import hr_hospital_visit
from . import hr_hospital_medical_diagnosis
from . import hr_hospital_doctor_specialty
from . import hr_hospital_doctor_schedule
from . import hr_hospital_patient_doctor_history
from . import hr_hospital_disease